### ISSUE TITLE
Shipping line stopped working, no longer adding to total

### ISSUE THREAD

**Issue by fish101022** [Invoice-Generator/invoice-generator-api#48]
I've been using your invoice generator for a long time, but sometime recently the shipping line stopped adding the shipping amount to the total. The discount and lines are working ok, they are subtracting as expected.

**Comment by jaredtking** [comment]
Can you provide an example of an API call with shipping that is not calculating the total correctly?

**Comment by fish101022** [comment]
Hi, thanks for the reply. Honestly I wouldn't know. I use the website
version.
https://invoice-generator.com/

I found that I can get around it by using the tax line and change it to
flat rate (instead of %), but that wouldn't work for someone who needs both
the shipping and tax additions.

I tried it on 2 different PCs and also different browsers just to be sure
it wasn't something on my PC. Same result regardless of which PC or browser.

Best regards,
Damian Sherrick
