### ISSUE TITLE
Romanian translation 🇷🇴

### ISSUE THREAD

**Issue by vladutilie** [Invoice-Generator/invoice-generator-api#59]
Hi guys,

I am willing to help you translate the invoice content into Romanian.
Please let me know how I can help.

Cheers,
Vlad

**Comment by jaredk2g** [comment]
I'm pleased to announce that Invoice-Generator.com is now available in Romanian! If you spot any issues with the translation then please let us know. Thank you!

**Comment by vladutilie** [comment]
Hello,

There are some missing translated strings and some of them are wrong or out of context.

<img width="1094" alt="image" src="https://github.com/Invoice-Generator/invoice-generator-api/assets/8014194/a2effa52-847a-4cdc-bb38-c3208f6e288a">

Regards.
