### ISSUE TITLE
render - gettext TypeError 

### ISSUE THREAD

**Issue by KoutnikM** [Invoice-Generator/invoice-generator-api#61]
I am trying to use your api on my website, it works properly with django on my laptop, but when I am trying to deploy the webapplicaton on render I am receiving this. When I delete your API it works right.

render -> Python 3.11

File "/opt/render/project/src/.venv/lib/python3.11/site-packages/InvoiceGenerator/conf.py", line 30, in <module>
    _ = get_gettext(lang)
        ^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/InvoiceGenerator/conf.py", line 13, in get_gettext
    t = gettext.translation(
        ^^^^^^^^^^^^^^^^^^^^
TypeError: translation() got an unexpected keyword argument 'codeset'

**Comment by jaredtking** [comment]
Since the python package is a separate repository and maintainer, please report your issue here: https://github.com/aleaforny/python-invoice-generator
