### ISSUE TITLE
invoice numbers dont appear once invoice is printed

### ISSUE THREAD

**Issue by Stratospher1** [Invoice-Generator/invoice-generator-api#69]
invoice numbers dont appear on printed copy once invoice is printed? Need  Help

**Comment by jaredtking** [comment]
Can you provide an API call that reproduces this issue?

**Comment by Stratospher1** [comment]
Jared,

 

Sorry I don’t know how to do that.  I am  just an end user. I have used Invoice generator for about 10 yrs with no issues.  The corresponding invoice number for every invoice is visible on the page ,but then the entire  box with the number should be  disappears when printed. It only shows the word invoice. 

 

Thank you

C.J
