### ISSUE TITLE
Increase the Cookie and Cache for Invoices

### ISSUE THREAD

**Issue by emcleod7** [Invoice-Generator/invoice-generator-api#70]
Ive been using the site for about a year with all invoices saved to the local cache & cookies and now I cant make anymore invoices. I think my cookies or cache is too large. Can you increase the acceptable size on your site? Here is a screenshot of my error. 

Here is a screenshot of what i get. 

![Error page](https://github.com/Invoice-Generator/invoice-generator-api/assets/168851452/d2e6a37c-c093-46c0-aca3-fb7e9f5b27ab)

The site works on chrome incognito mode or any other browser.

**Comment by jaredtking** [comment]
You might have a browser plugin installed that is causing the issue. Invoices are stored in LocalStorage and cookies are not used. When a request is made then your invoices are not sent with the request. Therefore the size of your invoices in LocalStorage should not matter. It could be a different problem though!

**Comment by emcleod7** [comment]
I went ahead and deleted all Chrome extensions and it still didnt fix the issue. Any other thoughts or ideas on how to fix this error?

**Comment by emcleod7** [comment]
It something in the cookies because i downloaded my cookies and uploaded my cookies to a seperate laptop with Chrome, and the error returned.

**Comment by jaredtking** [comment]
I would not copy your cookies over as they are not needed. You only need to copy the data in Local Storage.

**Comment by emcleod7** [comment]
I see, chrome as a 10mb local storage limit. I need to figure out how to change it to unlimitedstorage. Any ideas on how to do that?

**Comment by jaredtking** [comment]
Unfortunately not

**Comment by emcleod7** [comment]
Do you know any browsers that have unlimited localstorage? I figure ill need to start over, but dont want to hit the same limit again.

**Comment by jaredkng** [comment]
We introduced a new Cloud Mode where your invoices are stored securely in the cloud using your free Invoice-Generator.com account instead of to your browser's localStorage. While an account is not required to use Invoice-Generator.com it could potentially solve this issue where you are keeping track of a large number of invoices because as you've seen you are otherwise at the mercy of the storage available in your web browser.

**Comment by emcleod7** [comment]
Thats great!  I will definitely start using this. Now is there a way to start my invoice number where my old ones left off? I noticed that when I logged in, it restarted my invoice number back to 1. How can I have it start counting where I left off ?

**Comment by jaredk2g** [comment]
You can now edit the next number in the settings. On the next invoice number field there is an edit button that will allow you to change this. Hope it helps!

**Comment by emcleod7** [comment]
It does! Thank you so much. I just used the feature.
