### ISSUE TITLE
Query slowdown

### ISSUE THREAD

**Issue by kevinturpin97** [Invoice-Generator/invoice-generator-api#72]
Hi, since the api keys appeared I have noticed a slowdown in services for invoice generations, what is this due to? Key checks? If this is the case, would it be possible to correct it please?

**Comment by jaredk2g** [comment]
Can you quantify what slow means to you?

**Comment by kevinturpin97** [comment]
Yes, some generations taking much longer (5-10 sec) but sometimes its work as well (~150ms).
I saw that sometimes the Logo is missing from PDF files too.

**Comment by jaredk2g** [comment]
Can you provide a sample API call that reproduces this issue?

**Comment by kevinturpin97** [comment]
Sure, there is the body and header with fake data:
Header: 
`
[
  "Accept-Language: fr-FR",
  "Content-Type: application/json",
  "Content-Length: 646",
  "Authorization: Bearer sk_OO8sX8QNDzBu4iW6Xs2NUsjlyLQPkpcW"
]
`

Body:
`
{
  "header": "Facture N°112",
  "from": "FBh6V9hkpB Shop - Marie DUPONT",
  "to": "Philippe PAYET",
  "ship_to": "Aaz ADMIN, zazaza, Saint-Denis, Réunion, 97400",
  "logo": "https://api.ile-artisans.re/img/logo_256.png",
  "number": 112,
  "date": "03/06/2024",
  "items": [
    {
      "name": "SahB8hwfYO variantes 3",
      "unit_cost": 127.23,
      "quantity": 1,
      "description": "Résumé du XFyTeskUbG variantes\nCouleur: hSIuFN9vuR"
    }
  ],
  "fields": {
    "tax": false,
    "discounts": false,
    "shipping": false
  },
  "discounts": 0,
  "shipping": 0,
  "custom_fields": [
    {
      "name": "Statut",
      "value": "Payée"
    }
  ],
  "notes": "Ile Artisans - https://ile-artisans.re",
  "terms": "",
  "currency": "EUR",
  "amount_paid": 127.23
}
`

Each request is made with php cUrl

**Comment by jaredk2g** [comment]
That was very helpful, thank you. I've identified what is causing the sporadic slowdowns and think it has been fixed. Can you use this for a bit and report back if you still see the 10+ second generation times?

**Comment by kevinturpin97** [comment]
Perfect, thank you :)
