### ISSUE TITLE
Authorization through HTML form?

### ISSUE THREAD

**Issue by SquanchingInHere** [Invoice-Generator/invoice-generator-api#74]
We've been using invoice-generator for years, and we love it.

Unfortunately, the new authorization header requirement broke everything because we were using web forms to generate the invoices on the fly.

Is there any way to continue using web forms directly?

We would like to avoid having to create an internal endpoint just to add the authorization header.

**Comment by jaredk2g** [comment]
Unfortunately not. You can possibly use a JavaScript call to the API which would allow you to include your API key. Although I would not recommend this because it would expose your API key to any visitor.
