### ISSUE TITLE
wrong price notation when INR currency is used

### ISSUE THREAD

**Issue by joeydash** [Invoice-Generator/invoice-generator-api#75]
When using INR as currency, the prices and amounts are still displayed as US prices and amounts: 1,123,000.00 instead of Indian 11,23,000.00

The Indian numbering system differs from the Western system in the placement of commas. In the Indian style, commas are placed after every two digits, starting right after the first three digits. This system uses lakhs (100,000) and crores (10,000,000) instead of thousands and millions.

Explanation with Examples:
Lakhs and Crores:

1 Lakh: 100,000 is written as 1,00,000.
10 Lakhs: 1,000,000 is written as 10,00,000.
1 Crore: 10,000,000 is written as 1,00,00,000.
10 Crores: 100,000,000 is written as 10,00,00,000.
Currency Examples:

1,234 (one thousand two hundred thirty-four) is written as 1,234 in both systems.
12,345 (twelve thousand three hundred forty-five) is written as 12,345 in both systems.
123,456 (one hundred twenty-three thousand four hundred fifty-six) is written as 1,23,456 in the Indian system.
1,234,567 (one million two hundred thirty-four thousand five hundred sixty-seven) is written as 12,34,567 in the Indian system.
12,345,678 (twelve million three hundred forty-five thousand six hundred seventy-eight) is written as 1,23,45,678 in the Indian system.
Detailed Examples:
5,67,890: Five lakh sixty-seven thousand eight hundred ninety.
12,34,56,789: Twelve crore thirty-four lakh fifty-six thousand seven hundred eighty-nine.
Formatting Currency:
In Indian Rupees (INR), the format typically includes the currency symbol (₹) before the number. For example:

₹1,23,456.78: One lakh twenty-three thousand four hundred fifty-six rupees and seventy-eight paise.
₹12,34,56,789.00: Twelve crore thirty-four lakh fifty-six thousand seven hundred eighty-nine rupees and zero paise.
Summary:
Commas are placed after every two digits starting from the right after the first three digits.
The terms "lakhs" and "crores" are used instead of "thousands" and "millions".
Example: ₹12,34,56,789.00 (Indian system) vs. $12,345,678.00 (Western system).
This system is widely used in India for both numbers and currency representation, making it easier for people familiar with the system to read and understand large numbers.

**Comment by jaredk2g** [comment]
The number formatting is based on your browser's locale. You need to make sure your browser locale is set properly. If your browser locale is set to en-US for example, then that is why you see U.S. number formatting. Your browser locale should be set to India in order to see Indian number formatting.

**Comment by joeydash** [comment]
Thanks problem resolved!
