### ISSUE TITLE
2 issues; Ads and Sometimes auto save, sometimes does not auto save

### ISSUE THREAD

**Issue by nvalogos** [Invoice-Generator/invoice-generator-api#81]
2 questions for you, in regards to invoice-generator; 
1 -the ad pop-ups are constant and annoying, why are they happening more and more?

2 - When I am working on / in an invoice, sometimes it auto saves (as its supposed to), and sometimes it does not; it will just go away and pop me back to the history screen (where all invoices are listed), but that particular invoice I was working on is not there.

**Comment by jaredk2g** [comment]
Thank you for the feedback. However, this project is reserved for reporting issues related to the API.
